### ISSUE TITLE
CsvDataSource.getNextDataSet() throws NullPointerException

### ISSUE THREAD

**Issue by jsound** [mgm-tp/jfunk#18]
The CsvDataSource throws a NullPointerException when the last row of the csv file has been used:
java.lang.NullPointerException: null
    at java.util.HashMap.<init>(HashMap.java:318) ~[na:1.7.0_25]
    at com.google.common.collect.Maps.newHashMap(Maps.java:228) ~[guava-15.0.jar:na]
    at com.mgmtp.jfunk.data.DefaultDataSet.<init>(DefaultDataSet.java:48) ~[jfunk-data-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.data.source.CsvDataSource.getNextDataSetImpl(CsvDataSource.java:104) ~[jfunk-data-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.data.source.BaseDataSource.getNextDataSet(BaseDataSource.java:116) ~[jfunk-data-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.data.source.ContainerDataSource.getNextDataSet(ContainerDataSource.java:53) ~[jfunk-data-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.core.scripting.ScriptContext.prepareNextDataSet(ScriptContext.java:313) ~[jfunk-core-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.core.config.JFunkBaseModule$1.invoke(JFunkBaseModule.java:131) ~[jfunk-core-3.1.0-rc-2.jar:3.1.0-rc-2]
    at com.mgmtp.jfunk.unit.JFunkRunner.prepareNextDataSet(JFunkRunner.java:79) ~[jfunk-unit-3.1.0-rc-2.jar:3.1.0-rc-2]
A more more robust behaviour and a specific Exception would be the second best solution. I favor a solution where the DataSource restarts reading from the beginning of the csv file. With several independent CsvDataSources this behavior allows to increase the variation of test data (if the sizes of the csv files are not of same length or even coprime)

**Comment by blentorn** [comment]
Project is no longer active and will be archived
